name: Pat main workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  merge_group:
    types:
      - checks_requested
  push:
    branches: [main]
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  interpreter:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.2.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install system dependencies
        run: | 
          sudo apt-get update
          sudo apt install -y z3

      - name: Install pat dependencies
        run: >-
          opam install
          ./pat.opam
          --deps-only

      - name: Build pat from source
        run: |
          eval $(opam env)
          make
        shell: bash

      - name: Run testsuite
        run: |
          eval $(opam env)
          make test
        shell: bash
